name: Camera linux client

on:
  push:
    branches:
      - 'main'

jobs:
  build-camera-test:
    runs-on: ubuntu-22.04-arm
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ninja package
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      # Set up Java JDK (replace 17 with your version as required)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set up Flutter
        run: |
          git clone --depth 1 https://github.com/ardera/flutter-engine-binaries-for-arm.git engine-binaries
          cd engine-binaries
          sudo ./install.sh

      - name: Install packages
        run: flutter pub get

      - name: Build linux version
        run: flutter build linux --release --target-platform linux-arm64

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-camera-linux
          path: ./build/linux

