name: Camera linux client

on:
  push:
    branches:
      - 'main'

jobs:
  build-camera-test:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.27.1

      - name: Install packages
        run: flutter pub get

      - name: Build linux version
        run: flutter build linux --release --target-platform linux-arm64

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-camera-linux
          path: ./build/linux

