name: Camera linux client

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-camera-test:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install linux packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libopencv-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.27.1

      - name: Install flutter packages
        run: flutter pub get

      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor

      - name: Build linux version
        run: flutter_distributor release --name=dev --jobs=release-dev-linux-deb

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: build output
          path: ./build/linux

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb output
          path: ./dist

